-- SQL IS CASE INSENSITIVE BUT STANDARD IS TO WRITE IN ALL CAPS
-- * WILL SELECT EVERYTHING
SELECT * FROM EMPLOYEES;

-- SELECTING SPECIFIC COLUMNS BY PROVIDING COLUMN NAMES AND SEPARATING BY COMMA
-- IF TABLE OR COLUMN DOESN'T EXIST THEN IT WILL SHOW AN ERROR SUCH AS 'TABLE OR VIEW DOES NOT EXIST'
SELECT * FROM BREAKFAST;

SELECT * FROM COUNTRIES;

SELECT * FROM DEPARTMENTS;

SELECT * FROM JOBS;

SELECT * FROM LOCATIONS;

SELECT * FROM JOB_HISTORY;

-- DISPLAY ONLY THE FIRST NAME COLUMN OF EMPLOYEES TABLE
SELECT FIRST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;







