-- SQL IS CASE INSENSITIVE BUT STANDARD IS TO WRITE IN ALL CAPS
-- * WILL SELECT EVERYTHING
SELECT * FROM EMPLOYEES;

-- SELECTING SPECIFIC COLUMNS BY PROVIDING COLUMN NAMES AND SEPARATING BY COMMA
-- IF TABLE OR COLUMN DOESN'T EXIST THEN IT WILL SHOW AN ERROR SUCH AS 'TABLE OR VIEW DOES NOT EXIST'
SELECT * FROM BREAKFAST;

SELECT * FROM COUNTRIES;

SELECT * FROM DEPARTMENTS;

