SELECT DEPARTMENT_ID, ROUND(AVG(SALARY)) FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000;

SELECT DEPARTMENT_ID, ROUND(AVG(SALARY))
FROM EMPLOYEES
-- WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 6000 AND DEPARTMENT_ID IS NOT NULL ;

SELECT UPPER(FIRST_NAME), LENGTH(LAST_NAME), LENGTH(FIRST_NAME || LAST_NAME)  FROM EMPLOYEES
ORDER BY 3;



