SELECT C.COUNTRY_NAME, R.REGION_NAME FROM COUNTRIES C
INNER JOIN REGIONS R ON R.REGION_ID = C.REGION_ID;

SELECT E.FIRST_NAME, J.JOB_TITLE FROM EMPLOYEES E INNER JOIN JOBS J ON E.JOB_ID = J.JOB_ID;

SELECT D.DEPARTMENT_NAME, L.CITY FROM DEPARTMENTS D INNER JOIN LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID;